services:
  - type: web
    name: iris-cloud-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /ping
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
